apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: todo-app
type: Opaque
stringData:
  JWT_SECRET: "supersecret_jwt_key"
  MONGO_URI: "mongodb://mongo.todo-app.svc.cluster.local:27017/todo_db"