apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: todo-app
  labels:
    app: task-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task
          image: wojtek987/task-service:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: auth-secret
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10