# 18-metrics-server-fix.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  # Include the existing selector so the patch can merge
  selector:
    matchLabels:
      k8s-app: metrics-server

  template:
    metadata:
      # Include the existing pod labels
      labels:
        k8s-app: metrics-server

    spec:
      # Let it talk to kubelets directly
      hostNetwork: true

      containers:
        - name: metrics-server
          # Must re-declare the image
          image: k8s.gcr.io/metrics-server/metrics-server:v0.6.4

          # All flags needed for Kind/Docker Desktop clusters
          args:
            - --cert-dir=/tmp
            - --secure-port=4443
            - --kubelet-insecure-tls
            - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
            - --kubelet-use-node-status-port
            - --metric-resolution=15s

          ports:
            - containerPort: 4443